export type FinancialStatus='forecast'|'pending'|'approved'|'scheduled'|'partial'|'paid'|'received'|'overdue'|'cancelled';
export interface FinancialMetadata{companyId:string;createdAt:string;updatedAt:string;createdBy:string;status:FinancialStatus;deletedAt?:string}
export interface FinancialDimension{companyName?:string;branchId?:string;contractId?:string;contractName?:string;projectId?:string;projectName?:string;costCenterId?:string;costCenterName?:string;category?:string;responsibleUserId?:string;organizationName?:string;organizationCnpj?:string;bankAccountId?:string}
export interface AccountsReceivable extends FinancialMetadata,FinancialDimension{id:string;description:string;documentNumber?:string;invoiceNumber?:string;issueDate:string;dueDate:string;expectedDate:string;competence:string;grossAmount:number;discounts:number;withholdings:number;interest:number;fine:number;disallowance:number;netAmount:number;receivedAmount:number;balance:number;notes?:string}
export interface AccountsPayable extends FinancialMetadata,FinancialDimension{id:string;description:string;supplierName:string;supplierDocument?:string;documentNumber?:string;issueDate:string;dueDate:string;expectedDate:string;competence:string;grossAmount:number;discounts:number;interest:number;fine:number;withholdings:number;netAmount:number;paidAmount:number;balance:number;paymentMethod?:string;approver?:string;notes?:string}
export type TransactionKind='income'|'expense'|'transfer'|'adjustment'|'reversal'|'investment'|'redemption'|'fee'|'interest'|'tax'|'withholding';
export interface FinancialMovement extends FinancialMetadata,FinancialDimension{id:string;description:string;kind:TransactionKind;date:string;competence:string;amount:number;originType?:string;originId?:string;reconciled:boolean;reversedAt?:string;notes?:string}
export interface FinancialDashboard{availableBalance:number;forecastBalance:number;receivable:number;receivableOverdue:number;payable:number;payableOverdue:number;monthIncome:number;monthExpense:number;monthResult:number;operatingMargin:number;unclassified:number;unreconciled:number}
export interface FinancialFilters{search?:string;status?:FinancialStatus|'all';from?:string;to?:string;organization?:string;category?:string}
export type NewReceivable=Omit<AccountsReceivable,'id'|'companyId'|'createdAt'|'updatedAt'|'createdBy'|'deletedAt'>;
export type NewPayable=Omit<AccountsPayable,'id'|'companyId'|'createdAt'|'updatedAt'|'createdBy'|'deletedAt'>;
