import React from 'react';
import {Bike,MapPin,PackageCheck,Truck} from 'lucide-react';
import type {EcommerceShippingSettings} from './ecommerceTypes';

const modes=[
  {id:'correios' as const,label:'API dos Correios',text:'Cotação por CEP com serviços PAC e SEDEX.',icon:Truck},
  {id:'own' as const,label:'Entrega própria',text:'Use sua equipe e limite a área atendida.',icon:Bike},
  {id:'fixed' as const,label:'Taxa fixa',text:'Uma tarifa única para as regiões autorizadas.',icon:PackageCheck},
];
const list=(value:string)=>value.split(/[,;\n]/).map(item=>item.trim()).filter(Boolean);

export const EcommerceDeliverySettings=({value,onChange}:{value:EcommerceShippingSettings;onChange:(value:EcommerceShippingSettings)=>void})=>{
  const set=(next:Partial<EcommerceShippingSettings>)=>onChange({...value,...next});
  const coverage=(key:keyof EcommerceShippingSettings['coverage'],raw:string)=>set({coverage:{...value.coverage,[key]:list(raw)}});
  return <section className="space-y-6 rounded-2xl border bg-white p-6 dark:border-white/10 dark:bg-white/[.04]"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-bold">Entrega e cálculo de frete</h2><p className="mt-1 text-sm text-slate-500">O checkout valida o CEP e o endereço antes de liberar a entrega.</p></div><label className="flex items-center gap-3 rounded-xl border px-4 py-3 font-bold"><input type="checkbox" checked={value.enabled} onChange={e=>set({enabled:e.target.checked})}/>Habilitar entregas</label></div>
  <div className="grid gap-3 lg:grid-cols-3">{modes.map(item=><button key={item.id} onClick={()=>set({mode:item.id})} className={`rounded-2xl border p-5 text-left ${value.mode===item.id?'border-blue-500 bg-blue-50 ring-2 ring-blue-100':'hover:border-slate-300'}`}><item.icon className={value.mode===item.id?'text-blue-600':'text-slate-400'}/><b className="mt-4 block">{item.label}</b><small className="mt-1 block leading-5 text-slate-500">{item.text}</small></button>)}</div>
  <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3"><Field label="CEP de origem"><input value={value.originPostalCode||''} onChange={e=>set({originPostalCode:e.target.value.replace(/\D/g,'').slice(0,8)})} placeholder="60000000" className="input-field"/></Field><Field label="Prazo estimado (dias)"><input type="number" min="0" value={value.estimatedDays||0} onChange={e=>set({estimatedDays:Number(e.target.value)})} className="input-field"/></Field><Field label="Frete grátis acima de"><Money value={value.freeOverCents||0} onChange={freeOverCents=>set({freeOverCents})}/></Field>{value.mode!=='correios'&&<Field label="Taxa de entrega"><Money value={value.fixedFeeCents||0} onChange={fixedFeeCents=>set({fixedFeeCents})}/></Field>}{value.mode==='correios'&&<><Field label="Serviços"><select multiple value={value.correios?.services||['03220','03298']} onChange={e=>set({correios:{...value.correios,services:Array.from(e.target.selectedOptions).map(option=>option.value)}})} className="input-field h-24"><option value="03220">SEDEX</option><option value="03298">PAC</option></select></Field><Field label="Código do contrato"><input value={value.correios?.contractCode||''} onChange={e=>set({correios:{...value.correios,services:value.correios?.services||[],contractCode:e.target.value}})} className="input-field"/><small className="mt-1 block text-slate-500">As credenciais secretas ficam apenas no backend.</small></Field><Field label="Taxa provisória sem credencial"><Money value={value.correios?.fallbackFeeCents||0} onChange={fallbackFeeCents=>set({correios:{...value.correios,services:value.correios?.services||[],fallbackFeeCents}})}/></Field></>}</div>
  <div className="rounded-2xl bg-slate-50 p-5"><div className="flex items-center gap-2"><MapPin size={18} className="text-blue-600"/><h3 className="font-bold">Cobertura geográfica</h3></div><p className="mt-1 text-xs text-slate-500">Separe por vírgula. Deixe um nível vazio para não restringi-lo.</p><div className="mt-4 grid gap-4 lg:grid-cols-3"><Field label="Estados (UF)"><textarea value={value.coverage.states.join(', ')} onChange={e=>coverage('states',e.target.value.toUpperCase())} placeholder="CE, RN, PB" className="input-field min-h-24"/></Field><Field label="Cidades"><textarea value={value.coverage.cities.join(', ')} onChange={e=>coverage('cities',e.target.value)} placeholder="Fortaleza, Caucaia" className="input-field min-h-24"/></Field><Field label="Bairros"><textarea value={value.coverage.neighborhoods.join(', ')} onChange={e=>coverage('neighborhoods',e.target.value)} placeholder="Aldeota, Centro" className="input-field min-h-24"/></Field></div></div></section>;
};

const Field=({label,children}:{label:string;children:React.ReactNode})=><label className="block text-sm font-bold">{label}<div className="mt-2 font-normal">{children}</div></label>;
const Money=({value,onChange}:{value:number;onChange:(value:number)=>void})=><div className="flex overflow-hidden rounded-xl border bg-white"><span className="bg-slate-50 px-3 py-3 text-slate-500">R$</span><input type="number" min="0" step="0.01" value={(value/100).toFixed(2)} onChange={e=>onChange(Math.round(Number(e.target.value||0)*100))} className="min-w-0 flex-1 px-3 outline-none"/></div>;
