import React from 'react';
import {ArrowLeft,ArrowRight,Check,Loader2,Store,X} from 'lucide-react';
import type {EcommercePublicCompany,EcommerceStore} from './ecommerceTypes';

interface Props {
  store:EcommerceStore;
  companies:EcommercePublicCompany[];
  saving:boolean;
  slugState:{checking:boolean;available?:boolean;reason?:string;normalized?:string};
  onChange:(store:EcommerceStore)=>void;
  onClose:()=>void;
  onFinish:()=>Promise<void>;
}

const steps=['Empresa','Aparência','Pagamentos','URL','Administrador','Revisão'];
const documentLabel=(value:string)=>{const digits=value.replace(/\D/g,'');return digits.length===14?digits.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,'$1.$2.$3/$4-$5'):value;};

export const EcommerceOnboarding:React.FC<Props>=({store,companies,saving,slugState,onChange,onClose,onFinish})=>{
  const [step,setStep]=React.useState(0);
  const selected=companies.find(item=>item.id===store.publicCompanyId)||companies[0];
  const set=(value:Partial<EcommerceStore>)=>onChange({...store,...value});
  const valid=[Boolean(selected),Boolean(store.name.trim()),Object.values(store.paymentMethods).some(Boolean),Boolean(store.storeSlug&&slugState.available),Boolean(store.administrator?.name&&store.administrator?.email),true][step];
  const chooseCompany=(id:string)=>{const company=companies.find(item=>item.id===id);set({publicCompanyId:id,name:company?.tradeName||company?.legalName||store.name,logoUrl:company?.logoUrl||store.logoUrl});};
  return <div className="fixed inset-0 z-[100] overflow-y-auto bg-slate-950/70 p-3 backdrop-blur-sm sm:p-6"><section className="mx-auto min-h-[calc(100vh-1.5rem)] max-w-5xl overflow-hidden rounded-3xl bg-white shadow-2xl sm:min-h-0"><header className="flex items-center justify-between border-b px-5 py-4 sm:px-8"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Primeiros passos</p><h2 className="mt-1 text-xl font-black sm:text-2xl">Configure sua loja online</h2></div><button onClick={onClose} aria-label="Fechar configuração" className="rounded-xl p-2 hover:bg-slate-100"><X/></button></header>
  <div className="grid lg:grid-cols-[230px_1fr]"><aside className="border-b bg-slate-50 p-4 lg:min-h-[560px] lg:border-b-0 lg:border-r lg:p-6"><div className="flex gap-2 overflow-x-auto lg:block">{steps.map((label,index)=><button key={label} onClick={()=>index<=step&&setStep(index)} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold lg:mb-2 lg:w-full ${index===step?'bg-blue-600 text-white':index<step?'text-emerald-700':'text-slate-400'}`}><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full text-xs ${index<step?'bg-emerald-100 text-emerald-700':index===step?'bg-white/20':'bg-slate-200'}`}>{index<step?<Check size={14}/>:index+1}</span>{label}</button>)}</div></aside>
  <main className="p-5 sm:p-8">
  {step===0&&<div><Title title="Qual empresa venderá na loja?" text="Selecione o CNPJ emitente. A logomarca e os dados públicos serão carregados deste cadastro."/><div className="mt-6 grid gap-3">{companies.map(company=><button key={company.id} onClick={()=>chooseCompany(company.id)} className={`flex items-center gap-4 rounded-2xl border p-4 text-left ${selected?.id===company.id?'border-blue-500 bg-blue-50 ring-2 ring-blue-100':'hover:border-slate-300'}`}><span className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-xl border bg-white">{company.logoUrl?<img src={company.logoUrl} className="h-full w-full object-contain p-1"/>:<Store className="text-slate-300"/>}</span><span><strong className="block">{company.tradeName||company.legalName}</strong><small className="text-slate-500">{documentLabel(company.document)} · {company.city}{company.state?` - ${company.state}`:''}</small></span>{selected?.id===company.id&&<Check className="ml-auto text-blue-600"/>}</button>)}{!companies.length&&<p className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">Cadastre uma empresa emitente no Perfil para continuar.</p>}</div></div>}
  {step===1&&<div><Title title="Aparência da loja" text="Personalize a identidade que seus clientes verão."/><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Nome fantasia"><input value={store.name} onChange={e=>set({name:e.target.value})} className="input"/></Field><Field label="Mensagem do header"><input value={store.headerMessage||''} onChange={e=>set({headerMessage:e.target.value})} placeholder="Frete rápido e compra segura" className="input"/></Field><Field label="Cor principal"><Color value={store.theme?.primaryColor||'#0ea5e9'} onChange={value=>set({theme:{...store.theme,primaryColor:value}})}/></Field><Field label="Cor secundária"><Color value={store.theme?.secondaryColor||'#06b6d4'} onChange={value=>set({theme:{...store.theme,secondaryColor:value}})}/></Field></div>{selected?.logoUrl&&<div className="mt-5 flex items-center gap-4 rounded-2xl bg-slate-50 p-4"><img src={selected.logoUrl} className="h-16 w-16 rounded-xl bg-white object-contain p-1"/><div><b>Logomarca da empresa</b><p className="text-sm text-slate-500">Para trocar, atualize a logomarca no cadastro da empresa.</p></div></div>}</div>}
  {step===2&&<div><Title title="Métodos de pagamento" text="Escolha como os clientes poderão pagar. A ativação real depende da aprovação do recebedor."/><div className="mt-6 grid gap-3">{([['pix','PIX'],['creditCard','Cartão de crédito'],['boleto','Boleto']] as const).map(([key,label])=><label key={key} className="flex items-center justify-between rounded-2xl border p-5 font-bold"><span>{label}</span><input type="checkbox" checked={store.paymentMethods[key]} onChange={e=>set({paymentMethods:{...store.paymentMethods,[key]:e.target.checked}})} className="h-5 w-5"/></label>)}</div></div>}
  {step===3&&<div><Title title="Endereço público" text="Escolha um endereço exclusivo, simples de divulgar e sem # na URL."/><label className="mt-7 block"><span className="text-sm font-bold">URL da loja</span><div className="mt-2 flex overflow-hidden rounded-xl border focus-within:border-blue-500"><span className="bg-slate-50 px-4 py-3 text-slate-500">blutecnologias.com.br/</span><input value={store.storeSlug} onChange={e=>set({storeSlug:e.target.value})} placeholder="nome-da-loja" className="min-w-0 flex-1 px-3 outline-none"/></div></label><p className={`mt-3 text-sm font-bold ${slugState.available?'text-emerald-600':slugState.available===false?'text-rose-600':'text-slate-500'}`}>{slugState.checking?'Verificando...':slugState.available?`✓ ${slugState.normalized} está disponível`:slugState.reason||'Use letras, números e hífen.'}</p></div>}
  {step===4&&<div><Title title="Administrador do e-commerce" text="Este usuário será responsável por catálogo, pedidos e configurações da loja."/><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Nome"><input value={store.administrator?.name||''} onChange={e=>set({administrator:{...store.administrator!,name:e.target.value}})} className="input"/></Field><Field label="E-mail"><input type="email" value={store.administrator?.email||''} onChange={e=>set({administrator:{...store.administrator!,email:e.target.value}})} className="input"/></Field></div><p className="mt-4 rounded-xl bg-blue-50 p-4 text-sm text-blue-800">Se o e-mail for diferente do usuário atual, o acesso ficará pendente até o convite ser aceito.</p></div>}
  {step===5&&<div><Title title="Tudo pronto para começar" text="Confira os principais dados. Você poderá alterá-los depois nas configurações."/><div className="mt-6 divide-y rounded-2xl border"><Summary label="Empresa" value={`${selected?.tradeName||selected?.legalName||'-'} · ${documentLabel(selected?.document||'')}`}/><Summary label="Loja" value={store.name}/><Summary label="URL" value={`blutecnologias.com.br/${slugState.normalized||store.storeSlug}`}/><Summary label="Pagamentos" value={Object.entries(store.paymentMethods).filter(([,enabled])=>enabled).map(([key])=>({pix:'PIX',creditCard:'Cartão',boleto:'Boleto'}[key])).join(', ')||'Nenhum'}/><Summary label="Administrador" value={`${store.administrator?.name} · ${store.administrator?.email}`}/></div></div>}
  <footer className="mt-8 flex items-center justify-between border-t pt-5"><button onClick={()=>step?setStep(step-1):onClose()} className="flex items-center gap-2 rounded-xl border px-4 py-3 font-bold"><ArrowLeft size={18}/>{step?'Voltar':'Configurar depois'}</button>{step<steps.length-1?<button disabled={!valid} onClick={()=>setStep(step+1)} className="flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-40">Continuar<ArrowRight size={18}/></button>:<button disabled={saving} onClick={onFinish} className="flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-3 font-bold text-white">{saving?<Loader2 size={18} className="animate-spin"/>:<Check size={18}/>}Concluir configuração</button>}</footer>
  </main></div></section></div>;
};

const Title=({title,text}:{title:string;text:string})=><div><h3 className="text-2xl font-black">{title}</h3><p className="mt-2 text-slate-500">{text}</p></div>;
const Field=({label,children}:{label:string;children:React.ReactNode})=><label className="block"><span className="text-sm font-bold">{label}</span><div className="mt-2">{children}</div></label>;
const Color=({value,onChange}:{value:string;onChange:(value:string)=>void})=><div className="flex rounded-xl border p-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-12 cursor-pointer border-0 bg-transparent"/><input value={value} onChange={e=>onChange(e.target.value)} className="min-w-0 flex-1 px-2 font-mono outline-none"/></div>;
const Summary=({label,value}:{label:string;value:string})=><div className="flex flex-col gap-1 p-4 sm:flex-row sm:justify-between"><b>{label}</b><span className="text-slate-600">{value}</span></div>;
