import { collection, deleteDoc, doc, getDocs, serverTimestamp, setDoc } from 'firebase/firestore';
import { db } from '../../services/firebase';
import type { ExternalOpportunity } from '../integrations/core/integrationTypes';
const id=(item:ExternalOpportunity)=>encodeURIComponent(`${item.source}:${item.externalId}`);
const localKey=(companyId:string)=>`blu:opportunity-favorites:${companyId}`;
const localItemsKey=(companyId:string)=>`blu:opportunity-favorite-items:${companyId}`;
const localList=(companyId:string)=>{try{return new Set<string>(JSON.parse(localStorage.getItem(localKey(companyId))||'[]'))}catch{return new Set<string>()}};
const localItems=(companyId:string)=>{try{return JSON.parse(localStorage.getItem(localItemsKey(companyId))||'[]') as ExternalOpportunity[]}catch{return[]}};
const localSave=(companyId:string,values:Set<string>)=>localStorage.setItem(localKey(companyId),JSON.stringify([...values]));
export const opportunityFavoritesService={
  async list(companyId:string){const local=localList(companyId);void getDocs(collection(db,'companies',companyId,'opportunityFavorites')).then((result)=>{result.docs.forEach((entry)=>local.add(String(entry.data().key)));localSave(companyId,local)}).catch(()=>{/* O usuário demonstrativo mantém o favorito localmente. */});return local;},
  async listItems(companyId:string):Promise<ExternalOpportunity[]>{const byKey=new Map(localItems(companyId).map((item)=>[`${item.source}:${item.externalId}`,item]));try{const result=await getDocs(collection(db,'companies',companyId,'opportunityFavorites'));result.docs.forEach((entry)=>{const data=entry.data();if(data.externalId)byKey.set(String(data.key),{externalId:String(data.externalId),source:data.source as ExternalOpportunity['source'],sourceUrl:data.sourceUrl||undefined,organizationName:String(data.organizationName||'Órgão não informado'),organizationCnpj:data.organizationCnpj||undefined,processNumber:data.processNumber||undefined,procurementNumber:data.procurementNumber||undefined,object:String(data.object||'Objeto não informado'),estimatedValue:data.estimatedValue||undefined,publicationDate:data.publicationDate||undefined,openingDate:data.openingDate||undefined,status:data.status||undefined,raw:data.raw||{}})})}catch{/* Fallback local. */}const values=[...byKey.values()];localStorage.setItem(localItemsKey(companyId),JSON.stringify(values));return values},
  async save(companyId:string,userId:string,item:ExternalOpportunity){const key=`${item.source}:${item.externalId}`;const local=localList(companyId);local.add(key);localSave(companyId,local);const items=localItems(companyId).filter((saved)=>`${saved.source}:${saved.externalId}`!==key);items.unshift(item);localStorage.setItem(localItemsKey(companyId),JSON.stringify(items));void setDoc(doc(db,'companies',companyId,'opportunityFavorites',id(item)),{key,userId,source:item.source,externalId:item.externalId,sourceUrl:item.sourceUrl||null,organizationName:item.organizationName,organizationCnpj:item.organizationCnpj||null,object:item.object,processNumber:item.processNumber||null,procurementNumber:item.procurementNumber||null,estimatedValue:item.estimatedValue||null,publicationDate:item.publicationDate||null,openingDate:item.openingDate||null,status:item.status||null,raw:item.raw||null,savedAt:serverTimestamp()}).catch(()=>{/* Fallback local para sessão demonstrativa sem Firebase Auth. */})},
  async remove(companyId:string,item:ExternalOpportunity){const local=localList(companyId);local.delete(`${item.source}:${item.externalId}`);localSave(companyId,local);localStorage.setItem(localItemsKey(companyId),JSON.stringify(localItems(companyId).filter((saved)=>`${saved.source}:${saved.externalId}`!==`${item.source}:${item.externalId}`)));void deleteDoc(doc(db,'companies',companyId,'opportunityFavorites',id(item))).catch(()=>{/* Fallback local. */})}
};
