import{addDoc,collection,doc,getDoc,getDocs,query,updateDoc,where}from'firebase/firestore';import{db}from'../../../services/firebase';import type{AccountsPayable,AccountsReceivable,FinancialFilters,FinancialMovement,NewPayable,NewReceivable}from'../domain/financialTypes';import type{FinancialPhaseOneRepository,FinancialRepositoryContext}from'../repositories/financialRepositories';
const clean=<T,>(value:T):T=>JSON.parse(JSON.stringify(value));const now=()=>new Date().toISOString();
const matches=(item:any,filters?:FinancialFilters)=>{if(!filters)return true;if(filters.status&&filters.status!=='all'&&item.status!==filters.status)return false;if(filters.from&&String(item.dueDate||item.date)<filters.from)return false;if(filters.to&&String(item.dueDate||item.date)>filters.to)return false;if(filters.search&&!JSON.stringify(item).toLowerCase().includes(filters.search.toLowerCase()))return false;return true};
export class FirebaseFinancialAdapter implements FinancialPhaseOneRepository{
 private async queryList<T>(name:string,context:FinancialRepositoryContext,filters?:FinancialFilters){const snapshot=await getDocs(query(collection(db,name),where('companyId','==',context.companyId)));return snapshot.docs.map(item=>({id:item.id,...item.data()}as T)).filter(item=>!(item as any).deletedAt&&matches(item,filters))}
 private async create(name:string,context:FinancialRepositoryContext,value:Record<string,unknown>){const stamp=now();const result=await addDoc(collection(db,name),clean({...value,companyId:context.companyId,createdBy:context.userId,createdAt:stamp,updatedAt:stamp}));return result.id}
 private async update(name:string,id:string,value:Record<string,unknown>){await updateDoc(doc(db,name,id),clean({...value,updatedAt:now()}))}
 listReceivables=async(context:FinancialRepositoryContext,filters?:FinancialFilters)=>{const current=await this.queryList<AccountsReceivable>('accountsReceivable',context,filters);if(current.length)return current;const clients=await this.queryList<any>('clients',context);const today=new Date().toISOString().slice(0,10);return clients.flatMap(client=>(client.cobrancas||[]).filter(Boolean).map((billing:any,index:number)=>{const amount=Number(billing.value||0);const received=billing.status==='received'?amount:0;const dueDate=billing.dueDate||String(billing.date||today).slice(0,10);return{id:`legacy:${client.id}:${billing.id||index}`,companyId:context.companyId,createdBy:billing.userId||context.userId,createdAt:billing.date||now(),updatedAt:billing.receivedAt||billing.date||now(),status:billing.status==='received'?'received':dueDate<today?'overdue':'pending',description:billing.title||'Cobrança enviada',organizationName:client.razaoSocial||client.name,organizationCnpj:client.cnpj,contractName:billing.solutionSelect,invoiceNumber:billing.invoiceNumber,issueDate:String(billing.date||today).slice(0,10),dueDate,expectedDate:dueDate,competence:String(billing.date||today).slice(0,7),grossAmount:amount,discounts:0,withholdings:0,interest:0,fine:0,disallowance:0,netAmount:amount,receivedAmount:received,balance:amount-received,companyName:billing.senderCompany,category:'Receitas de contratos públicos'}as AccountsReceivable})).filter(item=>matches(item,filters))};createReceivable=(context:FinancialRepositoryContext,value:NewReceivable)=>this.create('accountsReceivable',context,value);updateReceivable=async(_context:FinancialRepositoryContext,id:string,value:Partial<AccountsReceivable>)=>{if(!id.startsWith('legacy:'))return this.update('accountsReceivable',id,value);const[,clientId,billingId]=id.split(':');const reference=doc(db,'clients',clientId);const snapshot=await getDoc(reference);if(!snapshot.exists())throw new Error('Cliente da cobrança não encontrado.');const billings=(snapshot.data().cobrancas||[]).map((billing:any,index:number)=>String(billing.id||index)===billingId?{...billing,status:value.status==='received'?'received':billing.status,receivedAt:value.status==='received'?now():billing.receivedAt}:billing);await updateDoc(reference,{cobrancas:billings,updatedAt:now()})};
 listPayables=async(context:FinancialRepositoryContext,filters?:FinancialFilters)=>{const current=await this.queryList<AccountsPayable>('accountsPayable',context,filters);if(current.length)return current;const movements=await this.queryList<any>('financialTransactions',context);return movements.filter(item=>(item.kind||item.type)==='expense').map(item=>{const amount=Number(item.amount||0);const day=String(item.date||now()).slice(0,10);return{id:`legacy-tx:${item.id}`,companyId:context.companyId,createdBy:item.createdBy||item.userId||context.userId,createdAt:item.createdAt||day,updatedAt:item.updatedAt||day,status:'paid',description:item.description||'Saída financeira',supplierName:item.supplierName||'Fornecedor não informado',issueDate:day,dueDate:day,expectedDate:day,competence:item.competence||day.slice(0,7),grossAmount:amount,discounts:0,interest:0,fine:0,withholdings:0,netAmount:amount,paidAmount:amount,balance:0,category:item.category,companyName:item.company||item.companyName}as AccountsPayable}).filter(item=>matches(item,filters))};createPayable=(context:FinancialRepositoryContext,value:NewPayable)=>this.create('accountsPayable',context,value);updatePayable=(_context:FinancialRepositoryContext,id:string,value:Partial<AccountsPayable>)=>this.update('accountsPayable',id,value);
 listMovements=async(context:FinancialRepositoryContext,filters?:FinancialFilters)=>(await this.queryList<any>('financialTransactions',context,filters)).map(item=>({...item,kind:item.kind||(item.type==='income'?'income':'expense'),competence:item.competence||String(item.date||'').slice(0,7),reconciled:Boolean(item.reconciled),status:item.status||(item.type==='income'?'received':'paid')}as FinancialMovement));createMovement=(context:FinancialRepositoryContext,value:Omit<FinancialMovement,'id'|'companyId'|'createdAt'|'updatedAt'|'createdBy'>)=>this.create('financialTransactions',context,value);
}
