import React from 'react';
import { Building2, Check, ChevronLeft, ChevronRight, Loader2, Search, X } from 'lucide-react';
import { accountantPermissionPresets, type AccountantIdentity, type CompanyPermissionMap } from '../domain/companyAccess';
import { companyAccessService } from '../services/companyAccessService';

type Company = { id: string; name: string; document?: string };
const emptyIdentity: AccountantIdentity = { name: '', cpf: '', email: '', phone: '', crc: '', crcState: '', crcNumber: '' };

export const AccountantInviteModal: React.FC<{ onClose(): void; onSaved(): void }> = ({ onClose, onSaved }) => {
  const [step, setStep] = React.useState(1); const [identity, setIdentity] = React.useState(emptyIdentity);
  const [companies, setCompanies] = React.useState<Company[]>([]); const [selected, setSelected] = React.useState<string[]>([]);
  const [permissions, setPermissions] = React.useState<Record<string, CompanyPermissionMap>>({});
  const [checking, setChecking] = React.useState(false); const [existing, setExisting] = React.useState(false);
  const [saving, setSaving] = React.useState(false); const [error, setError] = React.useState('');
  React.useEffect(() => { companyAccessService.listManagedCompanies().then(setCompanies).catch((reason) => setError(reason?.message || 'Não foi possível carregar as empresas.')); }, []);
  const checkEmail = async () => { if (!identity.email) return; setChecking(true); setError(''); try { const result = await companyAccessService.findAccountant(identity.email); setExisting(result.exists); if (result.identity) setIdentity((value) => ({ ...value, ...result.identity } as AccountantIdentity)); } catch (reason: any) { setError(reason?.message || 'Não foi possível verificar o e-mail.'); } finally { setChecking(false); } };
  const toggleCompany = (id: string) => setSelected((value) => value.includes(id) ? value.filter((item) => item !== id) : [...value, id]);
  const applyPreset = (companyId: string, preset: keyof typeof accountantPermissionPresets) => setPermissions((value) => ({ ...value, [companyId]: structuredClone(accountantPermissionPresets[preset]) }));
  const submit = async () => { setSaving(true); setError(''); try { await companyAccessService.linkAccountant(identity, selected.map((companyId) => ({ companyId, permissions: permissions[companyId] || accountantPermissionPresets.fiscalFinance }))); onSaved(); onClose(); } catch (reason: any) { setError(reason?.message || 'Não foi possível conceder os acessos.'); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-[120] grid place-items-center bg-slate-950/55 p-4"><div className="max-h-[92vh] w-full max-w-4xl overflow-y-auto rounded-3xl border border-white/20 bg-white p-6 shadow-2xl dark:bg-slate-950">
    <div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">Contador multiempresa · Etapa {step} de 3</p><h2 className="mt-2 text-2xl font-bold">{step === 1 ? 'Identificar contador' : step === 2 ? 'Conceder acesso às empresas' : 'Permissões por empresa'}</h2></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-white/10"><X /></button></div>
    {error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm font-medium text-rose-700">{error}</p>}
    {step === 1 && <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="text-sm font-bold">E-mail global</span><div className="mt-1 flex gap-2"><input type="email" value={identity.email} onChange={(e) => setIdentity({ ...identity, email: e.target.value })} onBlur={checkEmail} className="min-w-0 flex-1 rounded-xl border px-4 py-3 dark:bg-slate-900"/><button type="button" onClick={checkEmail} disabled={checking} className="rounded-xl border px-4">{checking ? <Loader2 className="animate-spin"/> : <Search/>}</button></div></label>{existing && <p className="sm:col-span-2 rounded-xl bg-blue-50 p-4 text-sm font-medium text-blue-800">Este contador já possui uma conta no sistema. Um novo acesso será associado à conta existente.</p>}{[['name','Nome completo'],['cpf','CPF'],['phone','Telefone'],['crc','CRC'],['crcState','UF do CRC'],['crcNumber','Número do CRC']].map(([key,label]) => <label key={key}><span className="text-sm font-bold">{label}</span><input value={String(identity[key as keyof AccountantIdentity] || '')} onChange={(e) => setIdentity({ ...identity, [key]: e.target.value })} className="mt-1 w-full rounded-xl border px-4 py-3 dark:bg-slate-900"/></label>)}</div>}
    {step === 2 && <div className="mt-6 grid gap-3 sm:grid-cols-2">{companies.map((company) => <button type="button" key={company.id} onClick={() => toggleCompany(company.id)} className={`flex items-center gap-4 rounded-2xl border p-4 text-left ${selected.includes(company.id) ? 'border-blue-500 bg-blue-50 dark:bg-blue-950/30' : 'dark:border-white/10'}`}><span className="grid h-11 w-11 place-items-center rounded-xl bg-slate-100 dark:bg-white/10"><Building2/></span><span className="min-w-0 flex-1"><strong className="block truncate">{company.name}</strong><small className="text-slate-500">{company.document || 'CNPJ não informado'}</small></span>{selected.includes(company.id) && <Check className="text-blue-600"/>}</button>)}</div>}
    {step === 3 && <div className="mt-6 space-y-4">{selected.map((companyId) => { const company = companies.find((item) => item.id === companyId); const current = permissions[companyId] || accountantPermissionPresets.fiscalFinance; return <section key={companyId} className="rounded-2xl border p-5 dark:border-white/10"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-bold">{company?.name}</h3><p className="text-xs text-slate-500">Esta permissão vale somente para esta empresa. Alterações críticas ficam desativadas por padrão.</p></div><select onChange={(e) => applyPreset(companyId, e.target.value as keyof typeof accountantPermissionPresets)} defaultValue="fiscalFinance" className="rounded-xl border bg-white px-3 py-2 dark:bg-slate-900"><option value="fiscal">Somente Fiscal</option><option value="fiscalFinance">Fiscal + Financeiro</option><option value="complete">Contabilidade Completa</option></select></div><div className="mt-4 flex flex-wrap gap-2">{Object.entries(current).map(([module, actions]) => <span key={module} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-semibold dark:bg-white/10">{module}: {Object.entries(actions).filter(([,allowed]) => allowed).map(([action]) => action).join(', ')}</span>)}</div></section>; })}</div>}
    <footer className="mt-7 flex justify-between border-t pt-5 dark:border-white/10"><button type="button" disabled={step === 1} onClick={() => setStep((value) => Math.max(1, value - 1))} className="flex items-center gap-2 rounded-xl border px-4 py-3 disabled:opacity-30"><ChevronLeft size={17}/>Voltar</button>{step < 3 ? <button type="button" disabled={step === 1 ? !identity.email || !identity.name : !selected.length} onClick={() => setStep((value) => value + 1)} className="flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-40">Continuar<ChevronRight size={17}/></button> : <button type="button" disabled={saving} onClick={submit} className="flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">{saving && <Loader2 className="animate-spin" size={17}/>}Conceder acessos</button>}</footer>
  </div></div>;
};
