import React from 'react';
import { Building2, Check, ChevronDown, Search, Star, X } from 'lucide-react';
import { useBluAuth } from '../contexts/BluAuthContext';
import { useAccountantCompany } from '../contexts/AccountantCompanyContext';

const digits = (value?: string) => String(value || '').replace(/\D/g, '');
const normalized = (value?: string) => String(value || '').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();

export const AccountantCompanySwitcher: React.FC<{onCompanySelected?: (companyId: string) => void}> = ({onCompanySelected}) => {
  const {user} = useBluAuth(); const {company, companies, competence, setCompetence, selectCompany} = useAccountantCompany();
  const [open, setOpen] = React.useState(false); const [search, setSearch] = React.useState(''); const [filter, setFilter] = React.useState<'all'|'favorites'|'recent'>('all');
  const favoriteKey = `blu:accountant:favorites:${user?.id || 'anonymous'}`; const recentKey = `blu:accountant:recent:${user?.id || 'anonymous'}`;
  const [favorites, setFavorites] = React.useState<string[]>(() => JSON.parse(localStorage.getItem(favoriteKey) || '[]'));
  const recent = React.useMemo(() => JSON.parse(localStorage.getItem(recentKey) || '[]') as string[], [open, company?.companyId]);
  const query = normalized(search); const queryDigits = digits(search);
  const visible = React.useMemo(() => companies.filter((item) => {
    if (filter === 'favorites' && !favorites.includes(item.companyId)) return false;
    if (filter === 'recent' && !recent.includes(item.companyId)) return false;
    if (!query) return true;
    return normalized(`${item.companyName} ${item.companyDocument || ''} ${(item as any).tradeName || ''} ${(item as any).city || ''} ${(item as any).responsibleName || ''} ${(item as any).internalCode || ''}`).includes(query) || (queryDigits && digits(item.companyDocument).includes(queryDigits));
  }).sort((a,b) => (favorites.includes(b.companyId) ? 1 : 0) - (favorites.includes(a.companyId) ? 1 : 0) || a.companyName.localeCompare(b.companyName, 'pt-BR')), [companies, query, queryDigits, filter, favorites, recent]);
  const toggleFavorite = (companyId: string) => { const next = favorites.includes(companyId) ? favorites.filter((item) => item !== companyId) : [...favorites, companyId]; setFavorites(next); localStorage.setItem(favoriteKey, JSON.stringify(next)); };
  return <><div className="flex min-w-0 items-center gap-2"><button aria-label={`Buscar e selecionar empresa. Empresa atual: ${company?.companyName || 'nenhuma'}`} onClick={() => setOpen(true)} className="flex min-w-0 flex-1 items-center gap-3 rounded-xl border border-slate-200 bg-white px-3 py-2 text-left dark:border-white/10 dark:bg-slate-900"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600 dark:bg-blue-500/15"><Building2 size={18}/></span><span className="min-w-0"><small className="block text-[10px] font-black uppercase tracking-wider text-slate-400">Empresa atual</small><strong className="block max-w-48 truncate text-sm">{company?.companyName || 'Selecionar empresa'}</strong></span><ChevronDown size={16} className="shrink-0 text-slate-400"/></button><input aria-label="Competência contábil global" type="month" value={competence} onChange={(event) => setCompetence(event.target.value)} className="min-w-0 rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-bold dark:border-white/10 dark:bg-slate-900"/></div>
  {open && <div className="fixed inset-0 z-[160] grid place-items-start bg-slate-950/55 p-4 pt-[8vh]" onMouseDown={(event) => {if (event.target === event.currentTarget) setOpen(false);}}><section className="mx-auto w-full max-w-3xl overflow-hidden rounded-3xl border border-white/20 bg-white shadow-2xl dark:bg-slate-950"><header className="flex items-center justify-between border-b p-5 dark:border-white/10"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Carteira contábil</p><h2 className="mt-1 text-xl font-bold">Selecionar empresa</h2></div><button onClick={() => setOpen(false)} className="rounded-xl p-2 hover:bg-slate-100 dark:hover:bg-white/10"><X/></button></header><div className="p-5"><label className="flex items-center gap-3 rounded-2xl border px-4 py-3 dark:border-white/10"><Search className="text-slate-400"/><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Razão social, nome fantasia, CNPJ, cidade..." className="w-full bg-transparent outline-none"/></label><div className="mt-4 flex gap-2">{([['all','Todas'],['favorites','Favoritas'],['recent','Recentes']] as const).map(([value,label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-full px-4 py-2 text-xs font-bold ${filter === value ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-500 dark:bg-white/10'}`}>{label}</button>)}</div></div><div className="max-h-[55vh] overflow-y-auto border-t dark:border-white/10">{visible.map((item) => <article key={item.id} className="flex items-center gap-3 border-b p-4 last:border-0 hover:bg-slate-50 dark:border-white/10 dark:hover:bg-white/[.04]"><button onClick={() => toggleFavorite(item.companyId)} aria-label={`${favorites.includes(item.companyId) ? 'Remover' : 'Adicionar'} ${item.companyName} dos favoritos`} className="rounded-lg p-2"><Star size={18} className={favorites.includes(item.companyId) ? 'fill-amber-400 text-amber-400' : 'text-slate-300'}/></button><button onClick={async () => {await selectCompany(item.companyId); onCompanySelected?.(item.companyId); setOpen(false);}} className="flex min-w-0 flex-1 items-center gap-3 text-left"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-500 dark:bg-white/10"><Building2 size={20}/></span><span className="min-w-0 flex-1"><strong className="block truncate">{item.companyName}</strong><small className="text-slate-500">{item.companyDocument || 'CNPJ não informado'} · {competence.split('-').reverse().join('/')}</small></span>{item.companyId === company?.companyId && <Check className="text-emerald-500"/>}</button></article>)}{!visible.length && <div className="p-12 text-center text-slate-500">Nenhuma empresa encontrada para esta busca.</div>}</div></section></div>}</>;
};
