import React, { useEffect, useState } from 'react';
import { AlertTriangle, Award, Building2, CheckCircle2, Download, ExternalLink, Eye, FileText, History, Landmark, ListChecks, Loader2, ReceiptText, X } from 'lucide-react';
import type { ExternalOpportunity } from '../integrations/core/integrationTypes'; import type { PncpOpportunityBundle } from '../integrations/pncp/pncpTypes'; import { integrationOpportunityService } from '../services/integrationOpportunityService';
import { awardClientSyncService, type AwardSyncResult } from '../services/awardClientSyncService';

type Tab='overview'|'process'|'items'|'results'|'documents'|'contracts'|'history'|'source';
const tabs:[Tab,string,React.ElementType][]=[['overview','Visão geral',Landmark],['process','Processo e órgão',Building2],['items','Itens',ListChecks],['results','Resultado',Award],['documents','Documentos',FileText],['contracts','Contratos',ReceiptText],['history','Histórico',History],['source','Dados da fonte',ExternalLink]];
const label=(key:string)=>key.replace(/([A-Z])/g,' $1').replace(/^./,(char)=>char.toUpperCase());
const display=(value:unknown)=>{if(value===null||value===undefined||value==='')return 'Não informado';if(typeof value==='boolean')return value?'Sim':'Não';if(typeof value==='object')return JSON.stringify(value);return String(value)};
const formatDateTime=(value:unknown)=>{if(!value)return 'Não informado';const date=new Date(String(value));return Number.isNaN(date.getTime())?display(value):new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'medium'}).format(date)};
const previewUrl=(url:string)=>{try{const parsed=new URL(url);const match=/^\/pncp-api\/(v1\/orgaos\/\d{14}\/compras\/\d{4}\/\d+\/arquivos\/\d+)$/.exec(parsed.pathname);return match?`/api/pncp/file/${match[1]}`:url}catch{return url}};
const Field=({name,value}:{name:string;value:unknown})=><div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{label(name)}</p><p className="mt-1 break-words text-sm font-medium text-slate-700">{display(value)}</p></div>;

export const OpportunityDetailsModal:React.FC<{opportunity:ExternalOpportunity;close:()=>void;initialTab?:Tab}>=({opportunity,close,initialTab='overview'})=>{const [tab,setTab]=useState<Tab>(initialTab);const [data,setData]=useState<PncpOpportunityBundle|null>(null);const [error,setError]=useState('');
  const [awardSync,setAwardSync]=useState<AwardSyncResult|null>(null);
  useEffect(()=>{if(opportunity.source==='tce-ce'){setData({detail:opportunity.raw as Record<string,unknown>,items:[],results:[],documents:[],history:[],contracts:[]});return;}integrationOpportunityService.getDetails(opportunity.externalId).then(async(bundle)=>{setData(bundle);if(bundle.results.length){try{setAwardSync(await awardClientSyncService.sync(opportunity,bundle))}catch(reason){console.error('Não foi possível conciliar o resultado com Clientes:',reason)}}}).catch((reason)=>setError(reason instanceof Error?reason.message:'Não foi possível carregar os detalhes.'))},[opportunity.externalId,opportunity.source]);
  return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/45 p-0 backdrop-blur-sm md:items-center md:p-6" role="dialog" aria-modal="true" aria-label="Detalhes da oportunidade"><section className="flex h-[94vh] w-full max-w-6xl flex-col overflow-hidden rounded-t-3xl bg-white shadow-2xl md:h-[88vh] md:rounded-3xl"><header className="border-b border-slate-200 px-5 py-4 md:px-7"><div className="flex items-start gap-4"><span className="hidden h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600 sm:grid"><Landmark size={20}/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-bold text-emerald-700">PNCP</span><span className="text-xs font-semibold text-slate-400">{opportunity.externalId}</span></div><h2 className="mt-2 line-clamp-2 text-lg font-bold leading-6 text-slate-950 md:text-xl">{opportunity.object}</h2><p className="mt-1 text-sm text-slate-500">{opportunity.organizationName}</p></div><button onClick={close} className="rounded-xl border border-slate-200 p-2 text-slate-500 hover:bg-slate-50" aria-label="Fechar detalhes"><X size={20}/></button></div></header><nav className="flex shrink-0 gap-1 overflow-x-auto border-b border-slate-200 px-4 py-2 md:px-7">{tabs.map(([id,name,Icon])=><button key={id} onClick={()=>setTab(id)} className={`flex shrink-0 items-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold ${tab===id?'bg-blue-50 text-blue-700':'text-slate-500 hover:bg-slate-50'}`}><Icon size={15}/>{name}</button>)}</nav><main className="flex-1 overflow-y-auto bg-[#f8fafc] p-5 md:p-7">{!data&&!error?<div className="grid h-full place-items-center"><div className="text-center"><Loader2 className="mx-auto animate-spin text-blue-600"/><p className="mt-3 text-sm text-slate-500">Carregando dados oficiais da oportunidade...</p></div></div>:error?<div className="mx-auto max-w-md rounded-2xl border border-rose-200 bg-rose-50 p-8 text-center"><AlertTriangle className="mx-auto text-rose-500"/><h3 className="mt-3 font-semibold">Detalhes indisponíveis</h3><p className="mt-1 text-sm text-rose-700">{error}</p></div>:data&&<TabContent tab={tab} data={data} opportunity={opportunity} awardSync={awardSync}/>}</main></section></div>};

const TabContent=({tab,data,opportunity,awardSync}:{tab:Tab;data:PncpOpportunityBundle;opportunity:ExternalOpportunity;awardSync:AwardSyncResult|null})=>{const detail=data.detail; if(tab==='overview')return <div className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-bold">Objeto da contratação</h3><p className="mt-3 text-sm leading-7 text-slate-700">{display(detail.objetoCompra||opportunity.object)}</p></section><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field name="modalidade" value={detail.modalidadeNome}/><Field name="situação" value={detail.situacaoCompraNome}/><Field name="valor total estimado" value={detail.valorTotalEstimado}/><Field name="modo de disputa" value={detail.modoDisputaNome}/><Field name="data publicação PNCP" value={detail.dataPublicacaoPncp}/><Field name="início das propostas" value={detail.dataAberturaProposta}/><Field name="fim das propostas" value={detail.dataEncerramentoProposta}/><Field name="critério de julgamento" value={detail.tipoInstrumentoConvocatorioNome}/></div></div>;
  if(tab==='process')return <ObjectGrid value={detail} exclude={['objetoCompra']}/>;
  if(tab==='items')return <Collection title="Itens da contratação" empty="Nenhum item publicado." items={data.items} preferred={['numeroItem','descricao','quantidade','unidadeMedida','valorUnitarioEstimado','valorTotal','situacaoCompraItemNome']}/>;
  if(tab==='results')return <Results items={data.results} sync={awardSync}/>;
  if(tab==='documents')return <Documents items={data.documents}/>;
  if(tab==='contracts')return <Collection title="Contratos e empenhos vinculados" empty="Nenhum contrato ou empenho vinculado." items={data.contracts} preferred={['numeroContratoEmpenho','objetoContrato','valorGlobal','dataVigenciaInicio','dataVigenciaFim','tipoContratoNome']}/>;
  if(tab==='history')return <Collection title="Histórico oficial" empty="Nenhum evento de histórico publicado." items={data.history} preferred={['dataAtualizacao','tipoEvento','descricao','justificativa']}/>;
  return <div className="space-y-4"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-800">Dados brutos recebidos da API oficial para rastreabilidade. Nenhuma informação foi alterada.</div><pre className="overflow-auto rounded-2xl bg-slate-950 p-5 text-xs leading-6 text-slate-200">{JSON.stringify(data,null,2)}</pre></div>};
const ObjectGrid=({value,exclude=[]}:{value:Record<string,unknown>;exclude?:string[]})=><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(value).filter(([key,val])=>!exclude.includes(key)&&typeof val!=='object').map(([key,val])=><Field key={key} name={key} value={val}/>)}</div>;
const Collection=({title,empty,items,preferred}:{title:string;empty:string;items:Array<Record<string,unknown>>;preferred:string[]})=><section><div className="mb-4 flex items-center justify-between"><h3 className="font-bold">{title}</h3><span className="rounded-full bg-slate-200 px-2.5 py-1 text-xs font-semibold text-slate-600">{items.length}</span></div>{items.length===0?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">{empty}</div>:<div className="space-y-3">{items.map((item,index)=><article key={index} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{preferred.filter((key)=>key in item).map((key)=><Field key={key} name={key} value={item[key]}/>)}</div></article>)}</div>}</section>;
const Results=({items,sync}:{items:Array<Record<string,unknown>>;sync:AwardSyncResult|null})=><section className="space-y-4">{sync&&(sync.status==='imported'||sync.status==='updated')&&<div className="flex gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800"><CheckCircle2 className="shrink-0" size={20}/><div><p className="text-sm font-bold">Vitória identificada para {sync.companyName}</p><p className="mt-1 text-xs">O órgão {sync.clientName} e o contrato foram {sync.status==='imported'?'adicionados':'atualizados'} em Clientes.</p></div></div>}<Collection title="Resultados homologados" empty="O PNCP ainda não publicou vencedor para os itens desta oportunidade." items={items} preferred={['numeroItem','nomeRazaoSocialFornecedor','niFornecedor','quantidadeHomologada','valorUnitarioHomologado','valorTotalHomologado','dataResultado','situacaoCompraItemResultadoNome']}/></section>;
const Documents=({items}:{items:Array<Record<string,unknown>>})=>{const [viewer,setViewer]=useState<{url:string;name:string}|null>(null);return <section><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Arquivos da oportunidade</h3><p className="mt-1 text-xs text-slate-500">Documentos oficiais publicados no PNCP, disponíveis para consulta e futura análise documental.</p></div><span className="rounded-full bg-slate-200 px-2.5 py-1 text-xs font-semibold text-slate-600">{items.length}</span></div>{items.length===0?<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">Nenhum arquivo foi publicado para esta oportunidade.</div>:<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="hidden grid-cols-[minmax(240px,1fr)_190px_180px_120px] gap-4 bg-slate-100 px-5 py-4 text-xs font-bold uppercase tracking-wide text-slate-600 md:grid"><span>Nome</span><span>Data/hora de inclusão</span><span>Tipo</span><span className="text-right">Ações</span></div><div className="divide-y divide-slate-200">{items.map((item,index)=>{const url=String(item.url||item.uri||item.link||'');const name=display(item.titulo||item.nome||`Documento ${index+1}`);const type=display(item.tipoDocumentoNome||item.tipoDocumentoDescricao||item.tipoDocumento);return <article key={String(item.sequencialDocumento||index)} className="grid gap-3 p-4 md:grid-cols-[minmax(240px,1fr)_190px_180px_120px] md:items-center md:gap-4 md:px-5"><div className="flex min-w-0 items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><FileText size={18}/></span><div className="min-w-0"><p className="truncate text-sm font-semibold text-slate-800" title={name}>{name}</p><p className="mt-0.5 text-xs text-slate-400 md:hidden">{type}</p></div></div><p className="text-xs text-slate-600 md:text-sm">{formatDateTime(item.dataPublicacaoPncp||item.dataInclusao)}</p><p className="hidden text-sm text-slate-600 md:block">{type}</p><div className="flex justify-end gap-1">{url.startsWith('http')?<><button type="button" onClick={()=>setViewer({url,name})} className="rounded-lg p-2 text-blue-600 hover:bg-blue-50" aria-label={`Ver ${name}`} title="Ver"><Eye size={18}/></button><a href={url} download className="rounded-lg p-2 text-blue-600 hover:bg-blue-50" aria-label={`Baixar ${name}`} title="Baixar"><Download size={18}/></a></>:<span className="text-xs text-slate-400">Indisponível</span>}</div></article>})}</div></div>}{viewer&&<DocumentViewer document={viewer} close={()=>setViewer(null)}/>}</section>};
const DocumentViewer=({document,close}:{document:{url:string;name:string};close:()=>void})=><div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/70 p-3 backdrop-blur-sm md:p-6" role="dialog" aria-modal="true" aria-label={`Visualização de ${document.name}`}><section className="flex h-[94vh] w-full max-w-6xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl"><header className="flex items-center gap-3 border-b border-slate-200 px-4 py-3 md:px-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-blue-50 text-blue-600"><FileText size={17}/></span><div className="min-w-0 flex-1"><h4 className="truncate text-sm font-bold text-slate-800" title={document.name}>{document.name}</h4><p className="text-xs text-slate-500">Visualização do arquivo publicado no PNCP</p></div><a href={document.url} download className="rounded-lg p-2 text-blue-600 hover:bg-blue-50" aria-label="Baixar arquivo" title="Baixar"><Download size={18}/></a><a href={document.url} target="_blank" rel="noreferrer" className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Abrir em nova guia" title="Abrir em nova guia"><ExternalLink size={18}/></a><button type="button" onClick={close} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Fechar visualização"><X size={20}/></button></header><div className="flex-1 bg-slate-200 p-1 md:p-3"><iframe src={previewUrl(document.url)} title={document.name} className="h-full w-full rounded-lg bg-white"/></div></section></div>;
