import React from 'react';
import { Building2, ChevronRight, FileWarning, Landmark, ReceiptText, Search, Star } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { useBluAuth } from '../contexts/BluAuthContext';

export const AccountantCompaniesPage: React.FC = () => {
  const { user, memberships, refreshMemberships, switchCompany } = useBluAuth(); const navigate = useNavigate(); const [search,setSearch]=React.useState(''); const [filter,setFilter]=React.useState<'all'|'favorites'>('all'); const [page,setPage]=React.useState(1); const perPage=24; const favoriteKey=`blu:accountant:favorites:${user?.id||'anonymous'}`; const [favorites,setFavorites]=React.useState<string[]>(()=>JSON.parse(localStorage.getItem(favoriteKey)||'[]'));
  React.useEffect(() => { void refreshMemberships(); }, []);
  const normalized=search.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const queryDigits=search.replace(/\D/g,'');const filtered=memberships.filter((item)=>(filter==='all'||favorites.includes(item.companyId))&&(!normalized||`${item.companyName} ${item.companyDocument||''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(normalized)||(queryDigits&&String(item.companyDocument||'').replace(/\D/g,'').includes(queryDigits))));const pages=Math.max(1,Math.ceil(filtered.length/perPage));const visible=filtered.slice((page-1)*perPage,page*perPage);const toggleFavorite=(id:string)=>{const next=favorites.includes(id)?favorites.filter((item)=>item!==id):[...favorites,id];setFavorites(next);localStorage.setItem(favoriteKey,JSON.stringify(next));};
  return <div className="mx-auto max-w-[1400px] space-y-6"><header><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Portal do contador</p><h1 className="mt-2 text-3xl font-bold">Minhas Empresas</h1><p className="mt-1 text-slate-500">{memberships.length} empresa(s) vinculada(s), sempre isoladas por contexto e permissão.</p></header><section className="flex flex-col gap-3 rounded-2xl border bg-white p-4 md:flex-row dark:border-white/10 dark:bg-white/[.04]"><label className="flex flex-1 items-center gap-3 rounded-xl border px-4 py-3 dark:border-white/10"><Search className="text-slate-400"/><input value={search} onChange={(event)=>{setSearch(event.target.value);setPage(1);}} placeholder="Buscar por razão social, nome fantasia ou CNPJ" className="w-full bg-transparent outline-none"/></label><div className="flex gap-2">{([['all','Todas'],['favorites','Favoritas']] as const).map(([value,label])=><button key={value} onClick={()=>{setFilter(value);setPage(1);}} className={`rounded-xl px-4 py-3 text-sm font-bold ${filter===value?'bg-blue-600 text-white':'bg-slate-100 text-slate-500 dark:bg-white/10'}`}>{label}</button>)}</div></section>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.map((membership) => <article key={membership.id} className="rounded-3xl border border-slate-200 bg-white/80 p-6 shadow-sm backdrop-blur dark:border-white/10 dark:bg-white/[0.06]"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-blue-600 dark:bg-blue-400/10"><Building2/></span><div className="flex items-center gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">ATIVO</span><button onClick={()=>toggleFavorite(membership.companyId)} aria-label="Favoritar empresa"><Star className={favorites.includes(membership.companyId)?'fill-amber-400 text-amber-400':'text-slate-300'} size={19}/></button></div></div><h2 className="mt-5 text-xl font-bold">{membership.companyName}</h2><p className="mt-1 text-sm text-slate-500">CNPJ: {membership.companyDocument || 'não informado'}</p><div className="mt-4 flex gap-2"><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500 dark:bg-white/10">Competência atual</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500 dark:bg-white/10">Sem alertas</span></div><button onClick={async () => { await switchCompany(membership.companyId); navigate('/admin/contador/central'); }} className="mt-6 flex w-full items-center justify-between rounded-xl bg-slate-950 px-4 py-3 font-bold text-white dark:bg-white dark:text-slate-950">Acessar empresa<ChevronRight size={18}/></button></article>)}</div>
    {pages>1&&<div className="flex items-center justify-center gap-3"><button disabled={page===1} onClick={()=>setPage(page-1)} className="rounded-xl border px-4 py-2 disabled:opacity-30">Anterior</button><span className="text-sm font-bold">Página {page} de {pages}</span><button disabled={page===pages} onClick={()=>setPage(page+1)} className="rounded-xl border px-4 py-2 disabled:opacity-30">Próxima</button></div>}
    {!memberships.length && <div className="rounded-3xl border border-dashed p-14 text-center"><Building2 className="mx-auto text-slate-300" size={48}/><h2 className="mt-4 font-bold">Nenhuma empresa vinculada</h2><p className="mt-1 text-sm text-slate-500">Solicite ao administrador que conceda acesso ao seu e-mail.</p></div>}
  </div>;
};

export const AccountantDashboardPage: React.FC = () => {
  const { user, memberships } = useBluAuth(); const navigate = useNavigate();
  const shortcuts = [{label:'Central contábil',to:'/admin/contador/central',icon:FileWarning},{label:'Financeiro',to:'/admin/financeiro',icon:Landmark},{label:'Notas fiscais',to:'/admin/financeiro/notas-fiscais',icon:ReceiptText}];
  return <div className="mx-auto max-w-[1400px] space-y-6"><header className="rounded-3xl border bg-white/70 p-7 backdrop-blur dark:border-white/10 dark:bg-white/[0.05]"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Empresa atual</p><h1 className="mt-2 text-3xl font-bold">{user?.companyName}</h1><p className="mt-1 text-slate-500">Visão contábil e fiscal conforme as permissões deste vínculo.</p></header><div className="grid gap-4 md:grid-cols-3">{shortcuts.map(({label,to,icon:Icon}) => <button key={to} onClick={() => navigate(to)} className="flex items-center gap-4 rounded-2xl border bg-white p-5 text-left dark:border-white/10 dark:bg-white/[0.05]"><Icon className="text-blue-600"/><span className="font-bold">{label}</span></button>)}</div>{memberships.length > 1 && <button onClick={() => navigate('/admin/empresas')} className="rounded-xl border px-4 py-3 font-bold">Trocar empresa</button>}</div>;
};
