import React from 'react';
import {CheckCircle2,Copy,ExternalLink,Globe2,Loader2,Package,Save,ShoppingBag,Store,WalletCards} from 'lucide-react';
import {useBluAuth} from '../contexts/BluAuthContext';
import {ecommerceService} from '../ecommerce/ecommerceService';
import {EcommerceOnboarding} from '../ecommerce/EcommerceOnboarding';
import {EcommerceDeliverySettings} from '../ecommerce/EcommerceDeliverySettings';
import type {EcommerceCatalogProduct,EcommercePublicCompany,EcommerceStore} from '../ecommerce/ecommerceTypes';
import {listCompanyDocs} from '../services/firestoreCompany';

const money=(cents:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);
const defaultShipping={enabled:false,mode:'fixed' as const,originPostalCode:'',fixedFeeCents:0,freeOverCents:0,estimatedDays:1,coverage:{states:[],cities:[],neighborhoods:[]},correios:{services:['03220','03298'],credentialsStatus:'not_configured',fallbackFeeCents:0}};
const empty=(companyId:string,companyName:string,user?:{id:string;name:string;email:string}):EcommerceStore=>({companyId,storeSlug:'',name:companyName||'Minha loja',description:'',headerMessage:'',status:'draft',paymentMethods:{pix:true,creditCard:true,boleto:false},maxInstallments:1,theme:{primaryColor:'#0ea5e9',secondaryColor:'#06b6d4',headerTextColor:'#ffffff'},shipping:defaultShipping,administrator:user?{userId:user.id,name:user.name,email:user.email,role:'ecommerce_admin',status:'active'}:undefined,onboarding:{completed:false}});
const tabs=['Visão Geral','URL da Loja','Produtos','Pagamentos','Entregas','Aparência','Meta'] as const;

export const EcommercePage:React.FC=()=>{
  const {user}=useBluAuth(); const [tab,setTab]=React.useState<(typeof tabs)[number]>('Visão Geral'); const [store,setStore]=React.useState<EcommerceStore|null>(null); const [products,setProducts]=React.useState<EcommerceCatalogProduct[]>([]); const [companies,setCompanies]=React.useState<EcommercePublicCompany[]>([]); const [showOnboarding,setShowOnboarding]=React.useState(false); const [loading,setLoading]=React.useState(true); const [saving,setSaving]=React.useState(false); const [message,setMessage]=React.useState(''); const [slugState,setSlugState]=React.useState<{checking:boolean;available?:boolean;reason?:string;normalized?:string}>({checking:false});
  const load=React.useCallback(async()=>{if(!user)return;setLoading(true);try{const result=await ecommerceService.admin(user.companyId);const initial=result.store||empty(user.companyId,user.companyName,user);const firstCompany=result.companies?.[0];if(!initial.publicCompanyId&&firstCompany){initial.publicCompanyId=firstCompany.id;initial.name=firstCompany.tradeName||firstCompany.legalName||initial.name;initial.logoUrl=firstCompany.logoUrl;}setStore(initial);setCompanies(result.companies||[]);setProducts(result.products);setShowOnboarding(!result.store);}catch{setStore(empty(user.companyId,user.companyName,user));const catalog=await listCompanyDocs<any>('products',user.companyId).catch(()=>[]);setProducts(catalog.map(item=>({id:item.id,name:item.name||'Produto',type:item.type||'product',active:item.active!==false,priceCents:Number(item.salePriceCents||0),stockQuantity:Number(item.stockQuantity||0),images:Array.isArray(item.images)?item.images.slice(0,3):[],published:item.salesChannels?.bluStore===true})));}finally{setLoading(false);}},[user]);React.useEffect(()=>{void load();},[load]);
  React.useEffect(()=>{if(store?.id||store?.status==='active')setShowOnboarding(false);},[store?.id,store?.status]);
  React.useEffect(()=>{if(!user||!store?.storeSlug){setSlugState({checking:false});return;}const timer=window.setTimeout(async()=>{setSlugState({checking:true});try{const result=await ecommerceService.checkSlug(user.companyId,store.storeSlug);setSlugState({checking:false,available:result.available,reason:result.reason,normalized:result.slug});}catch(e:any){setSlugState({checking:false,available:false,reason:e?.message});}},450);return()=>window.clearTimeout(timer);},[user?.companyId,store?.storeSlug]);
  if(loading||!store)return <div className="grid min-h-[450px] place-items-center"><Loader2 className="animate-spin text-blue-600"/></div>;
  const url=`https://blutecnologias.com.br/${slugState.normalized||store.storeSlug}`; const published=products.filter(p=>p.published).length; const checklist=[Boolean(store.name),Boolean(store.storeSlug&&slugState.available),published>0,store.paymentMethods.pix||store.paymentMethods.creditCard||store.paymentMethods.boleto,Boolean((store.shipping as any)?.configured),store.status==='active']; const progress=Math.round(checklist.filter(Boolean).length/checklist.length*100);
  const save=async(status:EcommerceStore['status']=store.status,override?:EcommerceStore)=>{if(!user)return;const value=override||store;setSaving(true);setMessage('');try{const result=await ecommerceService.saveStore(user.companyId,{...value,status,storeSlug:slugState.normalized||value.storeSlug});setStore({...value,status,storeSlug:result.storeSlug});setMessage(status==='active'?'Loja publicada com sucesso.':'Loja salva com sucesso.');}catch(e:any){const detail=String(e?.message||'');setMessage(/not-found|404|internal/i.test(detail)?'A função ecommerceStore ainda não foi publicada no Firebase. Publique a função para salvar e abrir a loja.':detail||'Não foi possível salvar a loja.');throw e;}finally{setSaving(false);}};
  return <div className="mx-auto max-w-[1500px] space-y-5">{showOnboarding&&<EcommerceOnboarding store={store} companies={companies} saving={saving} slugState={slugState} onChange={setStore} onClose={()=>setShowOnboarding(false)} onFinish={async()=>{const configured={...store,onboarding:{completed:true}};await save('draft',configured);setShowOnboarding(false);}}/>}<header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Canal de vendas</p><h1 className="mt-2 text-3xl font-bold">E-commerce Blu</h1><p className="mt-1 text-slate-500">Sua loja online conectada aos produtos, estoque e financeiro da empresa.</p></div><div className="flex flex-col gap-2 sm:flex-row"><button onClick={()=>setShowOnboarding(true)} className="rounded-xl border px-5 py-3 font-bold">Configurar loja</button><button onClick={()=>save(store.status==='active'?'draft':'active')} disabled={saving||slugState.checking||slugState.available===false||!store.storeSlug} className={`flex items-center justify-center gap-2 rounded-xl px-5 py-3 font-bold disabled:opacity-50 ${store.status==='active'?'border border-slate-200 bg-white text-slate-700':'bg-emerald-600 text-white'}`}>{store.status==='active'?'Retirar do ar':'Publicar loja'}</button><button onClick={()=>save()} disabled={saving||slugState.checking||slugState.available===false} className="flex items-center justify-center gap-2 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white disabled:opacity-50">{saving?<Loader2 size={18} className="animate-spin"/>:<Save size={18}/>}Salvar loja</button></div></header>
  {message&&<p className="rounded-xl bg-blue-50 p-4 text-sm font-semibold text-blue-800">{message}</p>}
  <section className="grid gap-5 xl:grid-cols-[240px_minmax(0,1fr)]">
    <section className="rounded-2xl border bg-white p-4 xl:hidden dark:border-white/10 dark:bg-white/[.04]"><label className="block text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">Seção do e-commerce<select value={tab} onChange={event=>setTab(event.target.value as (typeof tabs)[number])} className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-semibold normal-case text-slate-700 outline-none focus:border-blue-500 dark:border-white/10 dark:bg-white/10 dark:text-white">{tabs.map(item=><option key={item}>{item}</option>)}</select></label></section>
    <aside className="hidden h-fit rounded-2xl border bg-white p-2 xl:sticky xl:top-24 xl:block dark:border-white/10 dark:bg-white/[.04]"><p className="px-3 pb-2 pt-3 text-[10px] font-bold uppercase tracking-[.16em] text-slate-400">E-commerce</p>{tabs.map(item=><button key={item} onClick={()=>setTab(item)} className={`block w-full rounded-xl px-3 py-2.5 text-left text-sm font-semibold transition ${tab===item?'bg-blue-600 text-white':'text-slate-600 hover:bg-blue-50 hover:text-blue-700 dark:text-slate-300 dark:hover:bg-white/10 dark:hover:text-white'}`}>{item}</button>)}</aside>
    <main className="min-w-0 space-y-5">
  {tab==='Visão Geral'&&<><section className="grid gap-4 md:grid-cols-4"><Card icon={Store} label="Status" value={store.status==='active'?'Online':'Rascunho'}/><Card icon={Package} label="Produtos publicados" value={String(published)}/><Card icon={ShoppingBag} label="Pedidos hoje" value="0"/><Card icon={WalletCards} label="Faturamento hoje" value="R$ 0,00"/></section><section className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="rounded-2xl border bg-white p-6 dark:border-white/10 dark:bg-white/[.04]"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-wider text-blue-600">Loja online</p><h2 className="mt-2 text-2xl font-bold">{store.name}</h2><p className="mt-2 text-slate-500">{store.storeSlug?url:'Escolha o endereço público da loja.'}</p></div><Globe2 className="text-blue-600"/></div>{store.storeSlug&&<div className="mt-5 flex gap-2"><a href={`/${store.storeSlug}`} target="_blank" className="flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-bold text-white"><ExternalLink size={16}/>Abrir loja</a><button onClick={()=>navigator.clipboard.writeText(url)} className="flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-bold"><Copy size={16}/>Copiar link</button></div>}</div><div className="rounded-2xl border bg-white p-6 dark:border-white/10 dark:bg-white/[.04]"><div className="flex items-center justify-between"><h2 className="font-bold">Configuração</h2><strong className="text-blue-600">{progress}%</strong></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-blue-600" style={{width:`${progress}%`}}/></div>{['Nome da loja','Endereço','Produtos','Pagamentos','Entregas','Publicar'].map((label,index)=><p key={label} className="mt-3 flex items-center gap-2 text-sm"><CheckCircle2 size={16} className={checklist[index]?'text-emerald-500':'text-slate-300'}/>{label}</p>)}</div></section></>}
  {tab==='URL da Loja'&&<section className="rounded-2xl border bg-white p-6 dark:border-white/10 dark:bg-white/[.04]"><h2 className="text-xl font-bold">Endereço da loja</h2><p className="mt-1 text-sm text-slate-500">O endereço é exclusivo. Alterações mantêm redirecionamento do link anterior.</p><label className="mt-6 block max-w-3xl"><span className="text-sm font-bold">Escolha o endereço da sua loja</span><div className="mt-2 flex overflow-hidden rounded-xl border focus-within:border-blue-500"><span className="bg-slate-50 px-4 py-3 text-slate-500">blutecnologias.com.br/</span><input value={store.storeSlug} onChange={e=>setStore({...store,storeSlug:e.target.value})} placeholder="minha-loja" className="min-w-0 flex-1 px-3 outline-none"/></div></label><p className={`mt-3 text-sm font-bold ${slugState.available?'text-emerald-600':slugState.available===false?'text-rose-600':'text-slate-500'}`}>{slugState.checking?'Verificando disponibilidade...':slugState.available?`✓ ${slugState.normalized} está disponível`:slugState.reason||'Use letras, números e hífen.'}</p>{store.storeSlug&&<div className="mt-6 rounded-2xl bg-blue-50 p-5"><small className="font-bold uppercase text-blue-600">Sua loja ficará em</small><p className="mt-1 text-lg font-bold text-blue-950">{url}</p></div>}</section>}
  {tab==='Produtos'&&<section className="overflow-hidden rounded-2xl border bg-white dark:border-white/10 dark:bg-white/[.04]"><header className="border-b p-5"><h2 className="text-lg font-bold">Catálogo da loja</h2><p className="text-sm text-slate-500">Produtos e serviços usam o mesmo catálogo do ERP. Serviços aparecem em sua própria categoria.</p></header>{products.map(product=><article key={product.id} className="flex items-center gap-4 border-b p-4 last:border-0"><div className="h-14 w-14 overflow-hidden rounded-xl bg-slate-100">{product.images[0]&&<img src={product.images[0]} className="h-full w-full object-cover"/>}</div><div className="min-w-0 flex-1"><strong className="block truncate">{product.name}</strong><small className="text-slate-500">{money(product.priceCents)} · {product.type==='service'?'Serviço':`Estoque ${product.stockQuantity}`}</small></div><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={product.published} onChange={async e=>{const published=e.target.checked;setProducts(values=>values.map(item=>item.id===product.id?{...item,published}:item));try{await ecommerceService.publishProduct(user!.companyId,product.id,published);}catch{setProducts(values=>values.map(item=>item.id===product.id?{...item,published:!published}:item));}}}/>Loja Blu</label></article>)}{!products.length&&<p className="p-10 text-center text-slate-500">Cadastre produtos ou serviços no ERP para montar o catálogo.</p>}</section>}
  {tab==='Pagamentos'&&<section className="grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border bg-white p-6"><h2 className="text-xl font-bold">Meios de pagamento</h2>{([['pix','PIX'],['creditCard','Cartão de crédito'],['boleto','Boleto']] as const).map(([key,label])=><label key={key} className="mt-4 flex items-center justify-between rounded-xl border p-4 font-bold"><span>{label}</span><input type="checkbox" checked={store.paymentMethods[key]} onChange={e=>setStore({...store,paymentMethods:{...store.paymentMethods,[key]:e.target.checked}})}/></label>)}</div><div className="rounded-2xl border bg-white p-6"><p className="text-xs font-black uppercase tracking-wider text-blue-600">Pagar.me</p><h2 className="mt-2 text-xl font-bold">Ativar pagamentos online</h2><p className="mt-2 text-sm text-slate-500">O recebedor precisa concluir o onboarding e estar aprovado para receber vendas e utilizar split.</p><span className="mt-5 inline-flex rounded-full bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700">{store.recipient?.onboardingStatus||'Não iniciado'}</span></div></section>}
  {tab==='Meta'&&<section className="rounded-2xl border bg-white p-7"><p className="text-xs font-black uppercase tracking-wider text-blue-600">Integrações</p><h2 className="mt-2 text-2xl font-bold">Meta · Facebook + Instagram</h2><p className="mt-2 max-w-2xl text-slate-500">Provider preparado para OAuth, catálogos, preço e estoque. A Loja Blu continua operando caso a Meta esteja indisponível.</p><button disabled className="mt-6 rounded-xl bg-slate-200 px-5 py-3 font-bold text-slate-500">Conectar · configuração pendente</button></section>}
  {tab==='Aparência'&&<section className="space-y-6 rounded-2xl border bg-white p-6 dark:border-white/10 dark:bg-white/[.04]"><div><h2 className="text-xl font-bold">Identidade da loja</h2><p className="mt-1 text-sm text-slate-500">Defina a empresa emitente, o nome público e as cores da vitrine.</p></div><div className="grid gap-5 lg:grid-cols-2"><label><span className="text-sm font-bold">Empresa / CNPJ</span><select value={store.publicCompanyId||''} onChange={e=>{const company=companies.find(item=>item.id===e.target.value);setStore({...store,publicCompanyId:e.target.value,name:company?.tradeName||company?.legalName||store.name,logoUrl:company?.logoUrl||store.logoUrl});}} className="mt-2 w-full rounded-xl border bg-white px-4 py-3"><option value="">Selecione</option>{companies.map(company=><option key={company.id} value={company.id}>{company.tradeName||company.legalName} · {company.document}</option>)}</select></label><label><span className="text-sm font-bold">Nome fantasia</span><input value={store.name} onChange={e=>setStore({...store,name:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-blue-500"/></label><label className="lg:col-span-2"><span className="text-sm font-bold">Mensagem do header</span><input value={store.headerMessage||''} onChange={e=>setStore({...store,headerMessage:e.target.value})} placeholder="Compra segura, entrega rápida e atendimento próximo." className="mt-2 w-full rounded-xl border px-4 py-3 outline-none focus:border-blue-500"/></label><ColorSetting label="Cor principal" value={store.theme?.primaryColor||'#0ea5e9'} onChange={value=>setStore({...store,theme:{...store.theme,primaryColor:value}})}/><ColorSetting label="Cor secundária" value={store.theme?.secondaryColor||'#06b6d4'} onChange={value=>setStore({...store,theme:{...store.theme,secondaryColor:value}})}/><label><span className="text-sm font-bold">Administrador</span><input value={store.administrator?.name||''} onChange={e=>setStore({...store,administrator:{...store.administrator!,name:e.target.value}})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><label><span className="text-sm font-bold">E-mail do administrador</span><input type="email" value={store.administrator?.email||''} onChange={e=>setStore({...store,administrator:{...store.administrator!,email:e.target.value}})} className="mt-2 w-full rounded-xl border px-4 py-3"/></label></div>{store.logoUrl&&<div className="flex items-center gap-4 rounded-2xl bg-slate-50 p-4"><img src={store.logoUrl} className="h-16 w-16 rounded-xl bg-white object-contain p-1"/><p className="text-sm text-slate-600"><b className="block text-slate-900">Logomarca da empresa selecionada</b>A imagem é compartilhada com o cadastro público da empresa.</p></div>}</section>}
  {tab==='Entregas'&&<EcommerceDeliverySettings value={{...defaultShipping,...store.shipping,coverage:{...defaultShipping.coverage,...store.shipping?.coverage},correios:{...defaultShipping.correios,...store.shipping?.correios}}} onChange={shipping=>setStore({...store,shipping})}/>} 
    </main>
  </section>
  </div>;
};
const Card=({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string})=><article className="rounded-2xl border bg-white p-5 dark:border-white/10 dark:bg-white/[.04]"><div className="flex items-center justify-between"><span className="text-sm font-bold text-slate-500">{label}</span><Icon size={18} className="text-blue-600"/></div><p className="mt-3 text-2xl font-black">{value}</p></article>;
const ColorSetting=({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void})=><label><span className="text-sm font-bold">{label}</span><div className="mt-2 flex rounded-xl border p-2"><input type="color" value={value} onChange={e=>onChange(e.target.value)} className="h-10 w-12 cursor-pointer border-0 bg-transparent"/><input value={value} onChange={e=>onChange(e.target.value)} className="min-w-0 flex-1 px-2 font-mono outline-none"/></div></label>;
