import React,{useEffect,useState}from'react';
import{Check,Edit2,Loader2,Plus,Power,Save,Target,Trash2,X}from'lucide-react';
import{useBluAuth}from'../contexts/BluAuthContext';
import{interestSettingsService,type InterestArea}from'../services/interestSettingsService';

const empty=():InterestArea=>({id:`area-${Date.now()}`,name:'',keywords:[],active:true});
export const InterestSettingsPage:React.FC=()=>{const{user}=useBluAuth();const[areas,setAreas]=useState<InterestArea[]>([]);const[editing,setEditing]=useState<InterestArea|null>(null);const[term,setTerm]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[saved,setSaved]=useState(false);
  useEffect(()=>{if(!user)return;interestSettingsService.getAreas(user.companyId).then(setAreas).finally(()=>setLoading(false))},[user]);
  const addTerm=()=>{if(!editing)return;const value=term.trim();if(value&&!editing.keywords.some((item)=>item.toLowerCase()===value.toLowerCase()))setEditing({...editing,keywords:[...editing.keywords,value]});setTerm('')};
  const commit=()=>{if(!editing?.name.trim())return;const value={...editing,name:editing.name.trim(),keywords:[...new Set([editing.name.trim(),...editing.keywords.map((item)=>item.trim()).filter(Boolean)])]};setAreas((current)=>current.some((area)=>area.id===value.id)?current.map((area)=>area.id===value.id?value:area):[...current,value]);setEditing(null);setTerm('')};
  const persist=async()=>{if(!user)return;setSaving(true);await interestSettingsService.saveAreas(user.companyId,user.id,areas);setSaving(false);setSaved(true);window.setTimeout(()=>setSaved(false),1800)};
  if(loading)return <div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-blue-600"/></div>;
  return <div className="mx-auto max-w-5xl space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><Target/></span><div><h2 className="text-xl font-bold">Áreas de interesse</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Organize os segmentos em que sua empresa deseja participar. As áreas ativas filtram os objetos em Oportunidades e as novas publicações exibidas nas notificações.</p></div></div><button onClick={()=>setEditing(empty())} className="flex shrink-0 items-center justify-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white"><Plus size={17}/>Nova área</button></div>
    <div className="mt-7 space-y-3">{areas.length===0?<div className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center"><Target className="mx-auto text-slate-300"/><h3 className="mt-3 font-semibold">Nenhuma área cadastrada</h3><p className="mt-1 text-sm text-slate-500">Enquanto não houver áreas, todas as oportunidades serão apresentadas.</p></div>:areas.map((area)=><article key={area.id} className={`rounded-2xl border p-5 ${area.active?'border-slate-200 bg-white':'border-slate-200 bg-slate-50 opacity-70'}`}><div className="flex flex-col gap-4 sm:flex-row sm:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold text-slate-800">{area.name}</h3><span className={`rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${area.active?'bg-emerald-100 text-emerald-700':'bg-slate-200 text-slate-500'}`}>{area.active?'Ativa':'Pausada'}</span></div><div className="mt-3 flex flex-wrap gap-2">{area.keywords.map((keyword)=><span key={keyword} className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700">{keyword}</span>)}</div></div><div className="flex gap-1"><button onClick={()=>setAreas(areas.map((item)=>item.id===area.id?{...item,active:!item.active}:item))} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" title={area.active?'Pausar área':'Ativar área'}><Power size={17}/></button><button onClick={()=>setEditing({...area,keywords:[...area.keywords]})} className="rounded-lg p-2 text-blue-600 hover:bg-blue-50" title="Editar"><Edit2 size={17}/></button><button onClick={()=>setAreas(areas.filter((item)=>item.id!==area.id))} className="rounded-lg p-2 text-rose-500 hover:bg-rose-50" title="Excluir"><Trash2 size={17}/></button></div></div></article>)}</div>
    <div className="mt-6 flex justify-end"><button onClick={persist} disabled={saving} className="flex items-center gap-2 rounded-xl bg-[#0877ff] px-5 py-3 text-sm font-semibold text-white disabled:opacity-60">{saving?<Loader2 className="animate-spin" size={17}/>:saved?<Check size={17}/>:<Save size={17}/>} {saved?'Configuração salva':'Salvar configurações'}</button></div></section>
    {editing&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm"><section className="w-full max-w-xl rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-slate-100 p-5"><div><h3 className="font-bold">{areas.some((area)=>area.id===editing.id)?'Editar área':'Nova área de interesse'}</h3><p className="mt-1 text-xs text-slate-500">Informe o segmento e os termos que aparecem nos objetos das licitações.</p></div><button onClick={()=>setEditing(null)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={19}/></button></header><div className="space-y-5 p-5"><label className="block text-sm font-semibold text-slate-700">Nome da área<input autoFocus value={editing.name} onChange={(event)=>setEditing({...editing,name:event.target.value})} placeholder="Ex.: Tecnologia da Informação" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-blue-500"/></label><div><label className="text-sm font-semibold text-slate-700">Objetos e termos relacionados</label><div className="mt-2 flex gap-2"><input value={term} onChange={(event)=>setTerm(event.target.value)} onKeyDown={(event)=>{if(event.key==='Enter'){event.preventDefault();addTerm()}}} placeholder="Ex.: software, licença, suporte técnico" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 py-3 text-sm outline-none focus:border-blue-500"/><button onClick={addTerm} className="rounded-xl border border-slate-200 px-4 text-sm font-semibold">Adicionar</button></div><div className="mt-3 flex min-h-20 flex-wrap content-start gap-2 rounded-xl bg-slate-50 p-3">{editing.keywords.length===0?<span className="text-xs text-slate-400">Adicione termos para melhorar a correspondência.</span>:editing.keywords.map((keyword)=><span key={keyword} className="flex items-center gap-2 rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-slate-700 shadow-sm">{keyword}<button onClick={()=>setEditing({...editing,keywords:editing.keywords.filter((item)=>item!==keyword)})}><X size={13}/></button></span>)}</div></div><label className="flex items-center gap-3 text-sm font-medium text-slate-700"><input type="checkbox" checked={editing.active} onChange={(event)=>setEditing({...editing,active:event.target.checked})} className="h-4 w-4 rounded"/>Usar esta área nos filtros e notificações</label></div><footer className="flex justify-end gap-2 border-t border-slate-100 p-5"><button onClick={()=>setEditing(null)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancelar</button><button onClick={commit} disabled={!editing.name.trim()} className="rounded-xl bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-40">Salvar área</button></footer></section></div>}
  </div>};
