import React, { useState } from 'react';
import { ArrowLeft, ArrowRight, Building2, Check, PartyPopper, Target } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { BluLogo } from '../components/BluLogo';
import { useBluAuth } from '../contexts/BluAuthContext';

const goals = ['Encontrar licitações', 'Analisar editais', 'Organizar documentos', 'Controlar contratos', 'Acompanhar pagamentos', 'Melhorar o fluxo de caixa'];
const Field = ({ label, placeholder }: { label: string; placeholder: string }) => <label className="text-sm font-semibold text-slate-700">{label}<input placeholder={placeholder} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm font-normal outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-50"/></label>;

export const OnboardingPage: React.FC = () => {
  const [step, setStep] = useState(1); const [selectedGoals, setSelectedGoals] = useState<string[]>([]); const { signInDemo } = useBluAuth(); const navigate = useNavigate();
  const next = () => setStep((value) => Math.min(4, value + 1)); const back = () => setStep((value) => Math.max(1, value - 1));
  const finish = async () => { await signInDemo(); navigate('/admin/dashboard'); };
  return <div className="min-h-screen bg-[#f6f8fb]"><header className="flex h-[72px] items-center border-b border-slate-200 bg-white px-5 md:px-10"><BluLogo/><span className="ml-auto text-sm text-slate-500">Já tem uma conta? <button onClick={() => navigate('/admin/login')} className="font-semibold text-blue-600">Entrar</button></span></header>
    <main className="mx-auto max-w-3xl px-5 py-10 md:py-16"><div className="mb-10"><div className="flex items-center justify-between text-xs font-semibold"><span className="text-blue-600">Etapa {step} de 4</span><span className="text-slate-400">{step * 25}% concluído</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full rounded-full bg-[#0877ff] transition-all" style={{width:`${step * 25}%`}}/></div></div>
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm md:p-10">
        {step === 1 && <><div className="mb-8 flex items-start gap-4"><span className="rounded-xl bg-blue-50 p-3 text-blue-600"><Building2/></span><div><h1 className="text-2xl font-bold tracking-tight">Conte sobre sua empresa</h1><p className="mt-1 text-sm text-slate-500">Essas informações personalizam sua experiência na Blu.</p></div></div><div className="grid gap-5 md:grid-cols-2"><Field label="Razão social" placeholder="Distribuidora Nordeste Ltda."/><Field label="Nome fantasia" placeholder="Nome da empresa"/><Field label="CNPJ" placeholder="00.000.000/0001-00"/><Field label="Segmento" placeholder="Material hospitalar"/><Field label="Telefone" placeholder="(85) 99999-9999"/><div className="grid grid-cols-[1fr_90px] gap-3"><Field label="Cidade" placeholder="Fortaleza"/><Field label="Estado" placeholder="CE"/></div></div></>}
        {step === 2 && <><div className="mb-8"><h1 className="text-2xl font-bold tracking-tight">Como funciona sua operação?</h1><p className="mt-1 text-sm text-slate-500">Ajude a Blu a entender o tamanho e o alcance da sua equipe.</p></div><div className="grid gap-5 md:grid-cols-2"><Field label="Produtos vendidos" placeholder="Materiais, equipamentos..."/><Field label="Serviços prestados" placeholder="Instalação, manutenção..."/><Field label="Estados atendidos" placeholder="CE, RN, PB e PE"/><Field label="Pessoas na equipe" placeholder="6 a 10 pessoas"/><Field label="Licitações por mês" placeholder="Até 20"/><Field label="Contratos ativos" placeholder="5"/></div></>}
        {step === 3 && <><div className="mb-8 flex items-start gap-4"><span className="rounded-xl bg-blue-50 p-3 text-blue-600"><Target/></span><div><h1 className="text-2xl font-bold tracking-tight">Quais são seus objetivos?</h1><p className="mt-1 text-sm text-slate-500">Selecione tudo que você quer melhorar com a Blu.</p></div></div><div className="grid gap-3 md:grid-cols-2">{goals.map((goal) => { const active = selectedGoals.includes(goal); return <button key={goal} onClick={() => setSelectedGoals(active ? selectedGoals.filter((item) => item !== goal) : [...selectedGoals, goal])} className={`flex items-center gap-3 rounded-xl border p-4 text-left text-sm font-semibold transition ${active ? 'border-blue-500 bg-blue-50 text-blue-700' : 'border-slate-200 hover:border-slate-300'}`}><span className={`grid h-5 w-5 place-items-center rounded-md border ${active ? 'border-blue-600 bg-blue-600 text-white' : 'border-slate-300'}`}>{active && <Check size={13}/>}</span>{goal}</button>})}</div></>}
        {step === 4 && <div className="py-5 text-center"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-emerald-50 text-emerald-600"><PartyPopper size={30}/></div><h1 className="mt-6 text-3xl font-bold tracking-tight">Tudo pronto para começar</h1><p className="mx-auto mt-3 max-w-md text-slate-500">Seu ambiente está configurado. Você terá acesso completo ao plano Professional por 7 dias.</p><div className="mx-auto mt-8 max-w-md rounded-2xl bg-slate-50 p-5 text-left"><div className="flex justify-between border-b border-slate-200 pb-3 text-sm"><span className="text-slate-500">Empresa</span><strong>Distribuidora Nordeste Ltda.</strong></div><div className="flex justify-between pt-3 text-sm"><span className="text-slate-500">Avaliação</span><strong className="text-emerald-600">7 dias grátis</strong></div></div></div>}
        <div className="mt-10 flex justify-between border-t border-slate-100 pt-6"><button onClick={back} disabled={step === 1} className="flex items-center gap-2 px-3 py-2 text-sm font-semibold text-slate-500 disabled:invisible"><ArrowLeft size={17}/> Voltar</button><button onClick={step === 4 ? finish : next} className="flex items-center gap-2 rounded-xl bg-[#0877ff] px-5 py-3 text-sm font-semibold text-white">{step === 4 ? 'Acessar meu painel' : 'Continuar'} <ArrowRight size={17}/></button></div>
      </section></main></div>;
};
