"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.commandBudget = void 0;
const functions = require("firebase-functions");
const admin = require("firebase-admin");
const membership = async (uid) => { const s = await admin.firestore().collection('companyUsers').where('userId', '==', uid).limit(1).get(); return { companyId: s.empty ? `company-${uid}` : String(s.docs[0].data().companyId) }; };
const allowedStatuses = ['draft', 'analysis', 'pendingApproval', 'approved', 'rejected', 'revised', 'replaced', 'closed'];
const validateItems = (items) => items.map((item, index) => { const numbers = ['quantityMilliUnits', 'unitCostCents', 'unitPriceCents', 'taxCents', 'logisticsCents', 'additionalExpensesCents', 'totalCents', 'marginCents']; const taxPercent = Number(item.taxPercent || 0); if (!String(item.productService || '').trim() || !Number.isFinite(taxPercent) || taxPercent < 0 || numbers.some(key => !Number.isSafeInteger(Number(item[key])) || Number(item[key]) < 0))
    throw new functions.https.HttpsError('invalid-argument', `Item ${index + 1} inválido. Use valores inteiros em centavos.`); return { productService: String(item.productService), description: String(item.description || ''), quantityMilliUnits: Number(item.quantityMilliUnits), unit: String(item.unit || 'un'), unitCostCents: Number(item.unitCostCents), unitPriceCents: Number(item.unitPriceCents), taxPercent, taxCents: Number(item.taxCents), logisticsCents: Number(item.logisticsCents), additionalExpensesCents: Number(item.additionalExpensesCents), totalCents: Number(item.totalCents), marginCents: Number(item.marginCents) }; });
exports.commandBudget = functions.https.onCall(async (payload, context) => { if (!context.auth)
    throw new functions.https.HttpsError('unauthenticated', 'Faça login para continuar.'); const userId = context.auth.uid, m = await membership(userId), action = String(payload?.action || ''), budgetId = String(payload?.budgetId || ''), db = admin.firestore(), ref = budgetId ? db.collection('budgets').doc(budgetId) : db.collection('budgets').doc(); if (!['save', 'duplicate', 'approve', 'reject', 'replace', 'close'].includes(action))
    throw new functions.https.HttpsError('invalid-argument', 'Ação inválida.'); const existingItems = budgetId ? await db.collection('budgetItems').where('companyId', '==', m.companyId).where('budgetId', '==', budgetId).get() : null; await db.runTransaction(async (tx) => { const snapshot = budgetId ? await tx.get(ref) : null, before = snapshot?.exists ? snapshot.data() : null, previousRef = before?.previousVersionId ? db.collection('budgets').doc(String(before.previousVersionId)) : null, previousSnapshot = previousRef ? await tx.get(previousRef) : null; if (before && before.companyId !== m.companyId)
    throw new functions.https.HttpsError('permission-denied', 'Orçamento de outra empresa.'); const now = new Date().toISOString(); if (action === 'save') {
    const input = payload?.input || {}, items = validateItems(Array.isArray(input.items) ? input.items : []), { items: _transientItems, ...budgetInput } = input;
    if (!String(input.name || '').trim() || !String(input.code || '').trim() || !allowedStatuses.includes(input.status) || !items.length)
        throw new functions.https.HttpsError('invalid-argument', 'Nome, código, status e itens são obrigatórios.');
    if (before?.status === 'approved' || before?.status === 'replaced' || before?.status === 'closed')
        throw new functions.https.HttpsError('failed-precondition', 'Versões aprovadas, substituídas ou encerradas são imutáveis. Crie uma revisão.');
    const totalBudgetedCents = items.reduce((s, x) => s + x.totalCents, 0), totalCostCents = items.reduce((s, x) => s + (Math.round(x.unitCostCents * x.quantityMilliUnits / 1000) + x.taxCents + x.logisticsCents + x.additionalExpensesCents), 0), after = { ...budgetInput, companyId: m.companyId, rootBudgetId: before?.rootBudgetId || ref.id, totalBudgetedCents, totalCostCents, totalMarginCents: totalBudgetedCents - totalCostCents, realizedCents: Number(before?.realizedCents || 0), updatedAt: now, updatedBy: userId, ...(!before ? { createdAt: now, createdBy: userId } : {}) };
    tx.set(ref, after, { merge: false });
    existingItems?.docs.forEach(x => tx.delete(x.ref));
    items.forEach((item, index) => tx.set(db.collection('budgetItems').doc(), { ...item, companyId: m.companyId, budgetId: ref.id, position: index, createdAt: now, createdBy: userId }));
    tx.set(db.collection('financialAuditLogs').doc(), { companyId: m.companyId, action: before ? 'update' : 'create', entityType: 'budget', entityId: ref.id, userId, createdAt: now, before, after });
    return;
} if (!before)
    throw new functions.https.HttpsError('not-found', 'Orçamento não encontrado.'); if (action === 'duplicate') {
    const newRef = db.collection('budgets').doc(), versionNumber = Number(before.versionNumber || 1) + 1, after = { ...before, status: 'revised', versionNumber, previousVersionId: ref.id, rootBudgetId: before.rootBudgetId || ref.id, approvedAt: null, approvedBy: null, createdAt: now, createdBy: userId, updatedAt: now, updatedBy: userId };
    tx.set(newRef, after);
    existingItems?.docs.forEach(x => tx.set(db.collection('budgetItems').doc(), { ...x.data(), budgetId: newRef.id, createdAt: now, createdBy: userId }));
    tx.set(db.collection('financialAuditLogs').doc(), { companyId: m.companyId, action: 'duplicateVersion', entityType: 'budget', entityId: newRef.id, userId, createdAt: now, before: { sourceId: ref.id }, after });
    return;
} let status = action === 'approve' ? 'approved' : action === 'reject' ? 'rejected' : action === 'replace' ? 'replaced' : 'closed'; if (action === 'approve' && before.status !== 'pendingApproval')
    throw new functions.https.HttpsError('failed-precondition', 'Somente versões aguardando aprovação podem ser aprovadas.'); if (action === 'reject' && !String(payload.reason || '').trim())
    throw new functions.https.HttpsError('invalid-argument', 'A rejeição exige justificativa.'); const after = { ...before, status, updatedAt: now, updatedBy: userId, ...(action === 'approve' ? { approvedAt: now, approvedBy: userId } : {}), ...(action === 'reject' ? { rejectionReason: String(payload.reason || '') } : {}), ...(action === 'replace' ? { replacementBudgetId: String(payload.replacementBudgetId || '') } : {}), ...(action === 'close' ? { closedAt: now } : {}) }; tx.set(ref, after, { merge: false }); if (action === 'approve' && previousRef && previousSnapshot?.exists && previousSnapshot.data()?.companyId === m.companyId)
    tx.update(previousRef, { status: 'replaced', replacementBudgetId: ref.id, updatedAt: now, updatedBy: userId }); if (action === 'approve' && before.projectFinancials)
    tx.set(db.collection('budgetProjections').doc(ref.id), { companyId: m.companyId, budgetId: ref.id, projectId: before.projectId || '', contractId: before.contractId || '', costCenterId: before.costCenterId || '', periodStart: before.periodStart, periodEnd: before.periodEnd, amountCents: before.totalBudgetedCents, status: 'active', createdAt: now, createdBy: userId }); tx.set(db.collection('financialAuditLogs').doc(), { companyId: m.companyId, action, entityType: 'budget', entityId: ref.id, userId, createdAt: now, before, after }); }); return { id: ref.id }; });
//# sourceMappingURL=budgets.js.map