"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.commandDrePeriod = void 0;
const functions = require("firebase-functions");
const admin = require("firebase-admin");
const membership = async (uid) => { const s = await admin.firestore().collection('companyUsers').where('userId', '==', uid).limit(1).get(); return { companyId: s.empty ? `company-${uid}` : String(s.docs[0].data().companyId) }; };
exports.commandDrePeriod = functions.https.onCall(async (payload, context) => { if (!context.auth)
    throw new functions.https.HttpsError('unauthenticated', 'Faça login para continuar.'); const userId = context.auth.uid, m = await membership(userId), action = String(payload?.action || ''), from = String(payload?.from || ''), to = String(payload?.to || ''), regime = String(payload?.regime || 'accrual'); if (!['close', 'reopen'].includes(action) || !/\d{4}-\d{2}-\d{2}/.test(from) || !/\d{4}-\d{2}-\d{2}/.test(to) || !['cash', 'accrual'].includes(regime))
    throw new functions.https.HttpsError('invalid-argument', 'Período ou regime inválido.'); const id = `${m.companyId}_${regime}_${from}_${to}`, ref = admin.firestore().collection('drePeriodClosures').doc(id); await admin.firestore().runTransaction(async (tx) => { const snap = await tx.get(ref), before = snap.exists ? snap.data() : null, now = new Date().toISOString(); if (before && before.companyId !== m.companyId)
    throw new functions.https.HttpsError('permission-denied', 'Período de outra empresa.'); if (action === 'reopen' && !String(payload.reason || '').trim())
    throw new functions.https.HttpsError('invalid-argument', 'A reabertura exige justificativa.'); const after = { companyId: m.companyId, from, to, regime, status: action === 'close' ? 'closed' : 'open', closedAt: action === 'close' ? now : before?.closedAt || null, closedBy: action === 'close' ? userId : before?.closedBy || null, reopenedAt: action === 'reopen' ? now : null, reopenedBy: action === 'reopen' ? userId : null, reopenReason: action === 'reopen' ? String(payload.reason) : null, updatedAt: now, updatedBy: userId }; tx.set(ref, after, { merge: false }); tx.set(admin.firestore().collection('dreClosureHistory').doc(), { companyId: m.companyId, closureId: id, action, from, to, regime, reason: String(payload.reason || ''), createdAt: now, createdBy: userId }); tx.set(admin.firestore().collection('financialAuditLogs').doc(), { companyId: m.companyId, action: `drePeriod.${action}`, entityType: 'drePeriod', entityId: id, userId, createdAt: now, before, after }); }); return { id }; });
//# sourceMappingURL=dre.js.map